name: Deploy Documentation

on:
  workflow_dispatch:

jobs:
  build-deploy:
      defaults:
        run:
          shell: bash -l {0}

      runs-on: ubuntu-latest
      steps:
        - name: Check out project
          uses: actions/checkout@v4
          with:
            ref: ${{ github.ref }}

        - name: Initialize miniconda
          uses: conda-incubator/setup-miniconda@v3
          with:
            activate-environment: build
            auto-update-conda: true
            environment-file: environment.yml
            auto-activate-base: false
            python-version: 3.13

        - name: Conda config
          run: >-
            conda config --set always_yes yes
            --set changeps1 no

        - name: Install  and docs requirements
          run: |
            conda install --file requirements/conda.txt
            conda install --file requirements/docs.txt
            python -m pip install -e . --no-deps

        - name: build documents
          run: make -C doc html

        - name: Deploy
          uses: peaceiris/actions-gh-pages@v4
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./doc/build/html